spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sample_java
    username: root
    password: 123456

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8888